# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_shoplist_name1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoplist',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='shoplist',
            name='content4',
        ),
        migrations.RemoveField(
            model_name='shoplist',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='shoplist',
            name='name3',
        ),
        migrations.RemoveField(
            model_name='shoplist',
            name='src1',
        ),
    ]
