# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190304_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.CharField(default='mine.png', max_length=40),
        ),
    ]
