# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-15 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lunbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=256)),
                ('name', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Shoplist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('content1', models.CharField(max_length=255)),
                ('content2', models.CharField(max_length=255)),
                ('content3', models.CharField(max_length=255)),
                ('content4', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uphone', models.CharField(max_length=100, unique=True)),
                ('uname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
    ]
